//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advent2020.Business {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Advent2020.Business.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1889
        ///1974
        ///1983
        ///1590
        ///1530
        ///1402
        ///1731
        ///1935
        ///1404
        ///1763
        ///1733
        ///1234
        ///1706
        ///633
        ///1524
        ///880
        ///1970
        ///1815
        ///1766
        ///1587
        ///1329
        ///1386
        ///1769
        ///1709
        ///1816
        ///1672
        ///75
        ///1874
        ///1957
        ///1241
        ///1656
        ///1290
        ///1501
        ///1456
        ///1945
        ///1375
        ///1580
        ///1738
        ///1581
        ///1704
        ///1317
        ///1651
        ///1971
        ///1614
        ///1668
        ///1694
        ///1862
        ///562
        ///1497
        ///1460
        ///1768
        ///1797
        ///1828
        ///728
        ///1826
        ///1519
        ///1343
        ///1850
        ///1676
        ///1932
        ///1794
        ///1295
        ///1669
        ///1995
        ///1838
        ///1253
        ///1209
        ///1288
        ///1443
        ///1436
        ///1788
        ///1732
        ///1289
        ///74
        ///1659
        ///1264
        ///1533
        ///1938
        ///1401
        ///1748
        ///1445
        ///1941
        ///1924
        ///1807
        ///1772
        ///1761
        ///1805 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day1 {
            get {
                return ResourceManager.GetString("Day1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6-8 s: svsssszslpsp
        ///3-4 n: gncn
        ///4-8 v: vkvmvdmvhttvvrgvvwv
        ///16-18 j: jjjjjjjjjjjjjjjjjf
        ///13-15 p: pppppppvppppxxppp
        ///3-4 k: bkksggqbtwkkkzqcz
        ///8-18 x: qxphxxtczxxxxxrbxxl
        ///6-11 c: dccxcccccchrcfdckcsc
        ///10-11 c: ccvxccccccccc
        ///2-4 f: pszff
        ///18-20 z: zzzzzzzzzzwzzzzzzzzj
        ///1-7 g: ggggggpggggggg
        ///3-5 h: hhhhfhh
        ///2-5 x: dxxzxv
        ///7-8 s: ssssssss
        ///3-9 k: ktkkkkkklkck
        ///2-9 r: rzrrrrrrrrrrrr
        ///5-9 k: tkrkhkxbvkbkkkkk
        ///8-9 n: tnnpbnrns
        ///14-15 q: qqqqqqqqqqqqqqqq
        ///11-12 q: cqqqqqqqqqsqqqlqqqqq
        ///15-17 v: vvvvvvvvvvnvvv [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day2 {
            get {
                return ResourceManager.GetString("Day2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .........#..##..#..#........#..
        ///#...#..#..#...##.....##.##.#...
        ///....#..............#....#....#.
        ///#.#..#.....#...#.##..#.#.#.....
        ///........#..#.#..#.......#......
        ///.#........#.#..###.#....#.#.#..
        ///........#........#.......#.....
        ///...##..#.#.#........##.........
        ///#.#.##..###............#...#...
        ///............#....#.......###.##
        ///....##....##..#........#......#
        ///............#.#..........#.....
        ///#.#....#....##...#.....#.....#.
        ///......#.#.#...#.....###....#..#
        ///...........##..#.........#..#.#
        ///..#..#........... [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day3 {
            get {
                return ResourceManager.GetString("Day3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to byr:1971
        ///iyr:2017 hgt:160cm
        ///eyr:2020 ecl:hzl
        ///pid:157096267
        ///
        ///hgt:183cm
        ///pid:368895060
        ///ecl:oth eyr:2020
        ///iyr:2013
        ///byr:1966
        ///
        ///ecl:lzr cid:279 pid:192cm
        ///hcl:1f7352 iyr:2014 hgt:70cm eyr:1983
        ///byr:2004
        ///
        ///hcl:#602927 iyr:2018 byr:1938 ecl:blu
        ///eyr:2024 hgt:172cm
        ///pid:839621424
        ///
        ///ecl:#12f268
        ///hcl:#6b5442
        ///iyr:2012 byr:2011
        ///eyr:1933 pid:189cm hgt:155in
        ///
        ///byr:1954
        ///ecl:gry pid:664227667 eyr:2028
        ///hgt:151cm
        ///iyr:2019
        ///
        ///ecl:gry
        ///byr:1931 iyr:2017
        ///pid:459927933 eyr:2028
        ///hgt:67in hcl:#fffffd
        ///
        ///cid:322 h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day4 {
            get {
                return ResourceManager.GetString("Day4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BBFFFBBLLR
        ///BBFFFFFLRL
        ///BFBFFFBLRR
        ///FBBFFFFRLL
        ///FFBFFFBLRR
        ///BFBBBFFLLL
        ///BFBBBFFLRR
        ///FBBFBBFRLL
        ///BFFBFBBLLL
        ///BFBFBBFRRR
        ///FBFBFFBLLR
        ///FFFBBBFRLL
        ///BFBBFBBRRR
        ///FBFFBFBRRR
        ///BFFBFFFLLL
        ///FBBBFBFLRR
        ///BFBBFBFRLR
        ///BFFFFFBRRL
        ///BFFBFFFRLR
        ///FBBBBBFRLL
        ///BFBBFBBLRL
        ///BFFFBFBRLR
        ///FBBBBFBLLR
        ///BBFFFBFRRR
        ///BFFBBBFLRL
        ///BFBFBFFLLR
        ///FFFBBBFLLR
        ///BFBFFFFRRL
        ///FFFBBFBLLR
        ///FBFFFBFLRL
        ///FBBBFBBRLL
        ///FBBFBFFLLR
        ///FBFBBFFLLL
        ///FBBFFFFLLL
        ///BFBFFBFRRL
        ///FFBBBFBRLL
        ///BFFBBFFLLR
        ///BFBBBBBRLR
        ///BFFBFFFRLL
        ///FBBBBFFRRR
        ///FFBBBFFRRL
        ///BBFBFBBLRR
        ///BBFFFFFL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day5 {
            get {
                return ResourceManager.GetString("Day5", resourceCulture);
            }
        }
    }
}
